lang: "en" # all suported languages are listed in the "translations" folder in the config
serverName: "server" # the name for the database, if not needed leave as is
database:
  type: "mariadb"
  host: "localhost"
  port: 3306
  DBName: "BetterEnderChests"
  user: "enderchest"
  password: "YOUR-DATABASE-PASS-HERE"

configVersion: 2.1 # DO NOT DOUCH