lang: "en" # all suported languages are listed in the "translations" folder in the config
serverName: "server" # the name for the database, if not needed leave as is
database:
  url: "mariadb://localhost:3306/BetterEnderChests"
  user: "enderchest"
  password: "YOUR-DATABASE-PASS-HERE"

configVersion: 2.1 # DO NOT DOUCH